import type { Metadata } from 'next';
import { spaceGrotesk } from '@/styles/fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Axiom Nexus Agency',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${spaceGrotesk.className}`}>{children}</body>
    </html>
  );
}
